 
 		LIST P=16F877A
		INCLUDE <P16F877A.INC>
		__CONFIG _CP_OFF &_WDT_OFF &_HS_OSC &_PWRTE_OFF &_LVP_OFF

SAYAC0 EQU 20H
SAYAC1 EQU 21H
SAYAC2 EQU 22H
BIRLER EQU 23H
ONLAR EQU 24H
BINLER EQU 25H
YUZLER EQU 26H

;***********RESET VECTOR***********
	ORG 0
	GOTO START
;***********INTERRUPT VECTOR**********
	ORG 4
	GOTO START
;******MACRO TANIMLANABÝLÝR****KULLANILAN YERE KOPYALA/YAPIÞTIR
	BANK0 MACRO
	BCF STATUS,5
	ENDM 

	BANK1 MACRO
	BSF STATUS,5
	ENDM

START  BANK1
	MOVLW B'11110000';RD0-RD3 OUTPUT RD4-RD7 ARASI INPUT 
	MOVWF TRISD ;OLDU
	CLRF TRISB ;PORTB PÝNLERÝ OUTPUT OLDU
	
	BANK0
	CLRF PORTB
	CLRF PORTD 
	MOVLW D'0'
	MOVWF BINLER
	MOVLW D'0'
	MOVWF YUZLER
	MOVLW D'0'
	MOVWF ONLAR
	MOVLW D'0'
	MOVWF BIRLER

DONGU
	CALL GOSTER
	CALL TUSBUL
	GOTO DONGU
TUSBUL

	MOVLW B'11110111'
	MOVWF PORTD ;RD3 YANÝ 1. SATIR AKTÝF SATIR SECME
	CALL BEKLE  ;1,5 ms BEKLE
BUTON1
	BTFSC PORTD,4 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON2
	MOVLW D'0'
	MOVWF ONLAR
	MOVLW D'1'
	MOVWF BIRLER
	
	RETURN	
BUTON2
	BTFSC PORTD,5 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON3
	MOVLW D'0'
	MOVWF ONLAR
	MOVLW D'2'
	MOVWF BIRLER
	
	RETURN	
BUTON3
	BTFSC PORTD,6 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON4
	MOVLW D'0'
	MOVWF ONLAR
	MOVLW D'3'
	MOVWF BIRLER
	
	RETURN	

BUTON4
	BTFSC PORTD,7 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON5
	MOVLW D'0'
	MOVWF ONLAR
	MOVLW D'4'
	MOVWF BIRLER
	
	RETURN	
;*****************************2.SATIR********
BUTON5
	MOVLW B'11111011'
	MOVWF PORTD ;RD3 YANÝ 1. SATIR AKTÝF SATIR SECME
	CALL BEKLE  ;1,5 ms BEKLE

	BTFSC PORTD,4 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON6
	MOVLW D'0'
	MOVWF ONLAR
	MOVLW D'5'
	MOVWF BIRLER
	
	RETURN	
BUTON6
	BTFSC PORTD,5 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON7
	MOVLW D'0'
	MOVWF ONLAR
	MOVLW D'6'
	MOVWF BIRLER
	
	RETURN	
BUTON7
	BTFSC PORTD,6 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON8
	MOVLW D'0'
	MOVWF ONLAR
	MOVLW D'7'
	MOVWF BIRLER
	
	RETURN	

BUTON8
	BTFSC PORTD,7 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON9
	MOVLW D'0'
	MOVWF ONLAR
	MOVLW D'8'
	MOVWF BIRLER
	
	RETURN	
;************************3.SATIR********************
BUTON9
	MOVLW B'11111101'
	MOVWF PORTD ;RD3 YANÝ 1. SATIR AKTÝF SATIR SECME
	CALL BEKLE  ;1,5 ms BEKLE

	BTFSC PORTD,4 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON10
	MOVLW D'0'
	MOVWF ONLAR
	MOVLW D'9'
	MOVWF BIRLER
	
	RETURN	
BUTON10
	BTFSC PORTD,5 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON11
	MOVLW D'1'
	MOVWF ONLAR
	MOVLW D'0'
	MOVWF BIRLER
	
	RETURN	
BUTON11
	BTFSC PORTD,6 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON12
	MOVLW D'1'
	MOVWF ONLAR
	MOVLW D'1'
	MOVWF BIRLER
	
	RETURN	

BUTON12
	BTFSC PORTD,7 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON13
	MOVLW D'1'
	MOVWF ONLAR
	MOVLW D'2'
	MOVWF BIRLER
	
	RETURN	
;******************************4.SATIR*****************
BUTON13
	MOVLW B'11111110'
	MOVWF PORTD ;RD3 YANÝ 1. SATIR AKTÝF SATIR SECME
	CALL BEKLE  ;1,5 ms BEKLE

	BTFSC PORTD,4 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON14
	MOVLW D'1'
	MOVWF ONLAR
	MOVLW D'3'
	MOVWF BIRLER
	
	RETURN	
BUTON14
	BTFSC PORTD,5 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON15
	MOVLW D'1'
	MOVWF ONLAR
	MOVLW D'4'
	MOVWF BIRLER
	
	RETURN	
BUTON15
	BTFSC PORTD,6 ;RD4 0 ÝSE 1 ATLA
	GOTO BUTON16
	MOVLW D'1'
	MOVWF ONLAR
	MOVLW D'5'
	MOVWF BIRLER
	
	RETURN	

BUTON16
	BTFSC PORTD,7 ;RD4 0 ÝSE 1 ATLA
	RETURN 
	MOVLW D'1'
	MOVWF ONLAR
	MOVLW D'6'
	MOVWF BIRLER
	
	RETURN	

GOSTER
	MOVF BINLER,W ;W=ONLAR
	MOVWF PORTD
	MOVLW B'00000001'
	MOVWF PORTB
	CALL BEKLE

	
	MOVF YUZLER,W ;W=ONLAR
	MOVWF PORTD
	MOVLW B'00000010'
	MOVWF PORTB
	CALL BEKLE

	MOVF ONLAR,W ;W=ONLAR
	MOVWF PORTD
	MOVLW B'00000100'
	MOVWF PORTB
	CALL BEKLE

	
	MOVF BIRLER,W ;W=ONLAR
	MOVWF PORTD
	MOVLW B'00001000'
	MOVWF PORTD
	CALL BEKLE 
	CLRF PORTB

  RETURN
BEKLE;1,5ms GECIKME
	
	MOVLW .1
	MOVWF SAYAC0
BEKLE1
	MOVLW .50
	MOVWF SAYAC1
BEKLE2 
	MOVLW .50
	MOVWF SAYAC2
BEKLE3
	DECFSZ SAYAC2,F
	GOTO BEKLE3
	DECFSZ SAYAC1,F
	GOTO BEKLE2
	DECFSZ SAYAC0,F
	GOTO BEKLE1
	
	RETURN


	END
